// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlDBt4APKkkMFZ9OpVYVvT_-hA9UCNghM',
    appId: '1:554006651001:web:bb02b0fe042f691ec934a8',
    messagingSenderId: '554006651001',
    projectId: 'ner-landslide-ews',
    authDomain: 'ner-landslide-ews.firebaseapp.com',
    storageBucket: 'ner-landslide-ews.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEbymcm6-Y9O22uFHpg7ie5-YBqulAhF0',
    appId: '1:554006651001:android:beed66ec37f27367c934a8',
    messagingSenderId: '554006651001',
    projectId: 'ner-landslide-ews',
    storageBucket: 'ner-landslide-ews.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChTzcLmHA_Nn_OZCFNFObNlnrAdBms4nI',
    appId: '1:554006651001:ios:16c0d941d41bf888c934a8',
    messagingSenderId: '554006651001',
    projectId: 'ner-landslide-ews',
    storageBucket: 'ner-landslide-ews.firebasestorage.app',
    iosBundleId: 'com.ner.landslide.landslideEws',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChTzcLmHA_Nn_OZCFNFObNlnrAdBms4nI',
    appId: '1:554006651001:ios:16c0d941d41bf888c934a8',
    messagingSenderId: '554006651001',
    projectId: 'ner-landslide-ews',
    storageBucket: 'ner-landslide-ews.firebasestorage.app',
    iosBundleId: 'com.ner.landslide.landslideEws',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlDBt4APKkkMFZ9OpVYVvT_-hA9UCNghM',
    appId: '1:554006651001:web:99e0124d77d8c12ec934a8',
    messagingSenderId: '554006651001',
    projectId: 'ner-landslide-ews',
    authDomain: 'ner-landslide-ews.firebaseapp.com',
    storageBucket: 'ner-landslide-ews.firebasestorage.app',
  );
}
