/// Global app configuration. Flip [useMockData] to false once a real
/// Firebase project exists and lib/core/firebase_options.dart has been
/// regenerated by `flutterfire configure` — everything downstream
/// (AppState, the *Repository interfaces) reads this single flag.
class AppConfig {
  AppConfig._();

  static const bool useMockData = true;

  // Study area: Anini/Etalin, Dibang Valley, Arunachal Pradesh.
  // Do not change without re-validating against the source imagery/GIS data.
  static const double studyAreaMinLat = 28.60;
  static const double studyAreaMaxLat = 28.85;
  static const double studyAreaMinLng = 95.70;
  static const double studyAreaMaxLng = 96.00;

  static const double studyAreaCenterLat =
      (studyAreaMinLat + studyAreaMaxLat) / 2;
  static const double studyAreaCenterLng =
      (studyAreaMinLng + studyAreaMaxLng) / 2;

  static const double defaultMapZoom = 11.0;

  static const String district = 'Dibang Valley';
  static const String stateName = 'Arunachal Pradesh';

  static bool containsPoint(double lat, double lng) {
    return lat >= studyAreaMinLat &&
        lat <= studyAreaMaxLat &&
        lng >= studyAreaMinLng &&
        lng <= studyAreaMaxLng;
  }
}
